from collections.abc import Sequence

class NativeSandbox:
    def __init__(
        self,
        profile: str,
        filesystem_mode: str,
        allowlisted_commands: Sequence[str],
        session_state: str,
        workspace_root: str | None = None,
        writable_roots: list[str] | None = None,
        network_policy_json: str | None = None,
        event_callback: object | None = None,
        audit_callback: object | None = None,
    ) -> None: ...
    def run(
        self,
        mode: str,
        argv: list[str] | None,
        script: str | None,
        cwd: str | None,
        env: dict[str, str] | None,
        stdin: bytes | None,
        timeout_ms: int | None,
        metadata: dict[str, str] | None,
        network_enabled: bool | None,
        filesystem_mode: str | None,
    ) -> dict[str, object]: ...
    def exec_detached(
        self,
        mode: str,
        argv: list[str] | None,
        script: str | None,
        cwd: str | None,
        env: dict[str, str] | None,
        stdin: bytes | None,
        timeout_ms: int | None,
        metadata: dict[str, str] | None,
        network_enabled: bool | None,
        filesystem_mode: str | None,
    ) -> NativeRun: ...
    def read_file(self, path: str) -> bytes: ...
    def write_file(self, path: str, contents: bytes, create_parents: bool = False) -> None: ...
    def mkdir(self, path: str, parents: bool = False) -> None: ...
    def exists(self, path: str) -> bool: ...
    def audit_events(self) -> list[dict[str, object]]: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...

class NativeRun:
    @property
    def run_id(self) -> str: ...
    @property
    def started_at_ms(self) -> int: ...
    def status(self) -> str: ...
    def wait(self) -> dict[str, object]: ...
    def cancel(self) -> None: ...
    def stdout(self) -> str: ...
    def stderr(self) -> str: ...
    def output(self) -> str: ...
    def events(self) -> list[dict[str, object]]: ...
    def audit_events(self) -> list[dict[str, object]]: ...

def default_allowlisted_commands() -> list[str]: ...
def normalize_sandbox_path(path: str) -> str: ...
